name: fruits-and-vegetables
services:
  symfony:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - 8000:80
  storage:
    image: postgres:17.2-alpine3.21
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: MSj21Gn2Jn1f